"""Freeze-record helpers (R30), driven by ``scripts/freeze.sh``.

Two subcommands, both intended to be called from the freeze script rather than
by hand:

``schema-ddl``
    Print the PostgreSQL DDL for the ORM metadata. This is the *fallback* record
    of the database schema, used when ``pg_dump`` (or a reachable database) is
    not available: it is derived from ``jobrec.storage.models`` compiled against
    the PostgreSQL dialect, so it is deterministic and needs no live server.

``manifest``
    Write the final freeze manifest (``freeze_manifest.json``) that references
    the frozen commit hash and the dependency lock (R30.2), then write the
    unified ``checksums.json`` for the freeze bundle by reusing the R16
    checksum machinery (:func:`jobrec.evaluation.checksums.write_checksums`).

Environment/provenance fields (python, host, tracked dependency versions) are
taken from the existing run-manifest builder so there is one implementation of
those probes; the freeze manifest is a release-level artifact and keeps only the
parts of it that describe the frozen environment.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from jobrec.evaluation.checksums import sha256_of_file, write_checksums
from jobrec.evaluation.manifest import build_run_manifest
from jobrec.storage.migrations import CURRENT_SCHEMA_VERSION

#: Bumped only if the freeze-manifest layout changes incompatibly.
MANIFEST_SCHEMA_VERSION = 1


def _schema_ddl() -> str:
    """Return ``CREATE TABLE``/``CREATE INDEX`` DDL for the PostgreSQL dialect."""
    from sqlalchemy.dialects import postgresql
    from sqlalchemy.schema import CreateIndex, CreateTable

    from jobrec.storage import models  # noqa: F401  (registers tables on the metadata)
    from jobrec.storage.db import Base

    dialect = postgresql.dialect()
    lines = [
        "-- CMJCC database schema (source: SQLAlchemy metadata, PostgreSQL dialect).",
        "-- Generated by scripts/freeze.sh when pg_dump / a live database is unavailable.",
        f"-- schema_version: {CURRENT_SCHEMA_VERSION}",
        "",
    ]
    for table in Base.metadata.sorted_tables:
        lines.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            lines.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        lines.append("")
    return "\n".join(lines)


def _recorded_file(out_dir: Path, name: str | None) -> dict[str, Any] | None:
    """Return ``{"file": name, "sha256": ...}`` for a recorded artifact, if present."""
    if not name:
        return None
    path = out_dir / name
    if not path.is_file():
        return None
    return {"file": name, "sha256": sha256_of_file(path)}


def _build_manifest(args: argparse.Namespace) -> dict[str, Any]:
    out_dir = Path(args.out_dir)
    # build_run_manifest is total (never raises) and already probes the
    # interpreter, host and tracked dependency versions.
    env = build_run_manifest(None, None, None)

    lock = _recorded_file(out_dir, args.lock_file)
    if lock is not None:
        lock["tool"] = args.lock_tool

    schema: dict[str, Any] = {
        "source": args.schema_source,
        "schema_version": CURRENT_SCHEMA_VERSION,
    }
    schema_file = _recorded_file(out_dir, args.schema_file)
    if schema_file is not None:
        schema.update(schema_file)
    if args.schema_note:
        schema["note"] = args.schema_note

    return {
        "artifact": "cmjcc-freeze-manifest",
        "manifest_schema_version": MANIFEST_SCHEMA_VERSION,
        "generated_at": env["generated_at"],
        "tag": {
            "name": args.tag,
            "type": "annotated",
            "created": args.tag_state == "created",
            "pushed": args.pushed,
        },
        "commit": {
            "hash": args.commit,
            "short_hash": args.commit[:12] if args.commit else None,
            "branch": args.branch or None,
            "committed_at": args.committed_at or None,
            "worktree_clean": args.tree_state == "clean",
        },
        "dependency_lock": lock,
        "declared_dependencies": _recorded_file(out_dir, args.pyproject),
        "database_schema": schema,
        "run_instructions": _recorded_file(out_dir, args.instructions),
        "commit_record": _recorded_file(out_dir, args.commit_file),
        "environment": {
            "python": env["python"],
            "host": env["host"],
            "dependencies": env["dependencies"],
        },
    }


def _cmd_manifest(args: argparse.Namespace) -> int:
    out_dir = Path(args.out_dir)
    if not out_dir.is_dir():
        print(f"freeze: not a directory: {out_dir}", file=sys.stderr)
        return 1
    manifest = _build_manifest(args)
    target = out_dir / args.output
    target.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    # Unified checksums over the whole freeze bundle, manifest included (R16).
    checksums = write_checksums(out_dir)
    print(target.as_posix())
    print(checksums.as_posix())
    return 0


def _cmd_schema_ddl(_args: argparse.Namespace) -> int:
    sys.stdout.write(_schema_ddl())
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("schema-ddl", help="print PostgreSQL DDL from the ORM metadata")

    manifest = sub.add_parser("manifest", help="write freeze_manifest.json + checksums.json")
    manifest.add_argument("--out-dir", required=True)
    manifest.add_argument("--tag", required=True)
    manifest.add_argument("--commit", required=True)
    manifest.add_argument("--branch", default="")
    manifest.add_argument("--committed-at", default="")
    manifest.add_argument("--tree-state", choices=["clean", "dirty"], required=True)
    manifest.add_argument("--tag-state", choices=["created", "not-created"], required=True)
    manifest.add_argument("--pushed", action="store_true")
    manifest.add_argument("--schema-source", required=True)
    manifest.add_argument("--schema-file", default="schema.sql")
    manifest.add_argument("--schema-note", default="")
    manifest.add_argument("--lock-file", default="requirements.lock.txt")
    manifest.add_argument("--lock-tool", default="pip freeze --exclude-editable")
    manifest.add_argument("--pyproject", default="pyproject.toml")
    manifest.add_argument("--instructions", default="RUN_INSTRUCTIONS.md")
    manifest.add_argument("--commit-file", default="commit.txt")
    manifest.add_argument("--output", default="freeze_manifest.json")

    args = parser.parse_args(argv)
    if args.command == "schema-ddl":
        return _cmd_schema_ddl(args)
    return _cmd_manifest(args)


if __name__ == "__main__":
    raise SystemExit(main())
